[buildPlans.Miosevka]
family = "Miosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.Miosevka.variants]
  inherits = "ss20"

    [buildPlans.Miosevka.variants.design]
    i = "semi-tailed"
    j = "serifless"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    r = "hookless-serifless"
    t = "flat-hook"
    braille-dot = "round"
    asterisk = "turn-hex-low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright-tall"
    at = "threefold"
    percent = "rings-continuous-slash"
    pilcrow = "low"
    lig-ltgteq = "slanted"

    [buildPlans.Miosevka.variants.italic]
    one = "no-base-long-top-serif"
    two = "straight-neck-serifless"
    four = "open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "curly-serifless-crossbar"
    eight = "crossing"
    nine = "straight-bar"
    zero = "oval-tall-reverse-slashed"
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-interrupted-serifless"
    capital-e = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-m = "slanted-sides-hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-q = "crossing-curly-tailed"
    capital-r = "curly-open-serifless"
    capital-z = "curly-serifless-with-crossbar"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    g = "single-storey-serifed"
    i = "tailed-serifed"
    j = "serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "tailed-serifed"
    m = "short-leg-top-left-serifed"
    n = "straight-top-left-serifed"
    q = "diagonal-tailed-serifless"
    r = "serifless"
    t = "bent-hook"
    u = "tailed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-curly-serifless"
    z = "cursive"
    braille-dot = "round"
    asterisk = "penta-low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "slanted-open-tall"
    ampersand = "lower-open"
    at = "fourfold-tall"
    percent = "rings-segmented-slash"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.Miosevka.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Miosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Miosevka.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Miosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Miosevka.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.Miosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Miosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Miosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"