[buildPlans.Miosevka]
family = "Miosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Miosevka.variants]
  inherits = "ss20"

    [buildPlans.Miosevka.variants.design]
    f = "serifless"
    g = "single-storey-serifless"
    i = "serifed"
    l = "serifed"
    m = "short-leg-serifless"
    p = "eared-serifless"
    r = "serifless"
    t = "flat-hook"
    two = "curly-neck-serifless"
    five = "upright-flat-serifless"
    nine = "open-contour"
    tilde = "low"
    asterisk = "turn-hex-low"
    underscore = "high"
    caret = "medium"
    ascii-grave = "straight"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright-tall"
    at = "threefold"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"

    [buildPlans.Miosevka.variants.italic]
    capital-b = "more-asymmetric-serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-m = "slanted-sides-hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-q = "crossing-curly-tailed"
    capital-r = "straight-open-serifless"
    capital-z = "curly-serifless-with-horizontal-crossbar"
    a = "single-storey-tailed"
    b = "toothless-corner-serifless"
    c = "serifless"
    d = "toothless-corner-serifless"
    e = "rounded"
    f = "tailed"
    g = "single-storey-earless-corner"
    h = "straight-serifless"
    i = "tailed-serifed"
    j = "serifless"
    k = "diagonal-tailed-cursive-serifless"
    l = "tailed-serifed"
    m = "short-leg-top-left-serifed"
    n = "straight-top-left-serifed"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "hookless-serifless"
    s = "serifless"
    t = "bent-hook"
    u = "toothed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "curly-serifless"
    y = "cursive-serifless"
    z = "curly-serifless-with-crossbar"
    zero = "oval-tall-reverse-slashed"
    one = "no-base-long-top-serif"
    two = "straight-neck-serifless"
    three = "two-arcs"
    four = "open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "curly-serifless-crossbar"
    tilde = "low"
    asterisk = "penta-low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "slanted-open-tall"
    ampersand = "lower-open"
    at = "threefold"
    dollar = "interrupted"
    percent = "rings-segmented-slash"
    bar = "force-upright"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.Miosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Miosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Miosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Miosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Miosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"