[buildPlans.iosevka-sm]
family = "Iosevka_SM"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-sm.variants]
  inherits = "ss20"

    [buildPlans.iosevka-sm.variants.design]
    b = "toothed-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    i = "serifed"
    j = "serifless"
    l = "serifed"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "earless-rounded-straight-serifless"
    p = "eared-serifless"
    r = "serifless"
    t = "flat-hook-short-neck"
    u = "toothless-rounded-serifless"
    tilde = "low"
    asterisk = "turn-hex-low"
    underscore = "high"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright-tall"
    at = "threefold"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-grave = "straight"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"

    [buildPlans.iosevka-sm.variants.italic]
    capital-b = "more-asymmetric-serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-g = "toothed-serifless-hooked"
    capital-z = "cursive-with-crossbar"
    a = "single-storey-tailed"
    b = "toothless-corner-serifless"
    c = "serifless"
    d = "tailed-serifless"
    e = "rounded"
    f = "flat-hook-tailed"
    g = "single-storey-serifless"
    h = "tailed-serifless"
    i = "tailed"
    j = "serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "tailed-serifed"
    m = "short-leg-tailed-top-left-serifed"
    n = "tailed-motion-serifed"
    p = "earless-rounded-serifless"
    q = "tailed-serifless"
    r = "hookless-serifless"
    s = "serifless"
    t = "standard-short-neck2"
    u = "tailed-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "curly-serifless"
    y = "cursive-serifless"
    z = "curly-serifless-with-crossbar"
    zero = "dotted"
    two = "curly-neck"
    four = "open"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "curly-serifless-crossbar"
    tilde = "low"
    asterisk = "penta-low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "slanted-open-tall"
    ampersand = "lower-open"
    at = "threefold"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "with-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-sm.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-sm.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-sm.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-sm.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-sm.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-sm.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"