[buildPlans.Riosevka]
family = "Riosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Riosevka.variants]
  inherits = "ss20"

    [buildPlans.Riosevka.variants.design]
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifed"
    a = "single-storey-earless-corner-tailed"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    e = "rounded"
    f = "serifless"
    g = "single-storey-flat-hook-earless-rounded"
    i = "tailed-serifed"
    j = "serifed"
    l = "tailed-serifed"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "earless-rounded-straight-serifless"
    p = "earless-rounded-serifless"
    q = "earless-corner-straight-serifless"
    r = "serifless"
    s = "serifless"
    u = "toothless-rounded-serifless"
    one = "no-base"
    five = "upright-flat-serifless"
    nine = "open-contour"
    asterisk = "penta-low"
    brace = "curly-flat-boundary"
    lig-ltgteq = "flat"

    [buildPlans.Riosevka.variants.italic]
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-j = "descending-serifed"
    capital-k = "curly-serifless"
    capital-m = "hanging-serifless"
    capital-q = "curly-tailed"
    capital-z = "curly-serifless-with-crossbar"
    b = "toothed-serifless"
    d = "toothed-serifless"
    f = "tailed"
    g = "single-storey-earless-rounded"
    i = "tailed-serifed"
    j = "serifless"
    k = "diagonal-tailed-cursive-serifless"
    l = "tailed-serifed"
    m = "short-leg-top-left-serifed"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "compact-serifless"
    s = "serifless"
    t = "bent-hook"
    u = "toothed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "curly-serifless"
    z = "curly-serifless-with-horizontal-crossbar"
    five = "oblique-flat-serifless"
    six = "open-contour"
    seven = "curly-serifless-crossbar"
    nine = "open-contour"
    asterisk = "turn-hex-mid"
    ampersand = "lower-open"
    at = "fourfold-solid-inner-tall"
    dollar = "interrupted"
    cent = "through"
    percent = "rings-continuous-slash-also-connected"
    question = "smooth"
    pilcrow = "low"
    lig-ltgteq = "slanted"

[buildPlans.Riosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Riosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Riosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Riosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Riosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"